import { HistoryScreen, historyStyles } from "@/components/HistoryScreen";
import { createCompetitor, deleteCompetitor, getCompetitors, updateCompetitor, type Competitor, type CompetitorInput } from "@/services/competitors";
import { Ionicons } from "@expo/vector-icons";
import { useFocusEffect } from "expo-router";
import { useCallback, useState } from "react";
import { ActivityIndicator, Alert, KeyboardAvoidingView, Modal, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";

function CompetitorForm({ item, saving, onClose, onSave }: { item: Competitor | null; saving: boolean; onClose: () => void; onSave: (input: CompetitorInput) => void }) {
  const [username, setUsername] = useState(item?.username ?? "");
  const [displayName, setDisplayName] = useState(item?.displayName ?? "");
  const [notes, setNotes] = useState(item?.notes ?? "");
  const [error, setError] = useState<string | null>(null);
  function submit() {
    const normalized = username.trim().replace(/^@+/, "").toLowerCase();
    if (!/^[a-z0-9._]{1,30}$/.test(normalized)) { setError("Informe um username válido."); return; }
    if (displayName.trim().length > 160 || notes.trim().length > 2000) { setError("Revise o tamanho dos campos."); return; }
    onSave({ username: normalized, displayName: displayName.trim() || null, notes: notes.trim() || null });
  }
  return <KeyboardAvoidingView style={styles.overlay} behavior={Platform.OS === "ios" ? "padding" : undefined}><View style={styles.modal}><View style={styles.modalHeader}><Text style={styles.modalTitle}>{item ? "Editar referência" : "Nova referência"}</Text><TouchableOpacity style={styles.iconButton} onPress={onClose} accessibilityLabel="Fechar"><Ionicons name="close" size={24} color="#333" /></TouchableOpacity></View><ScrollView keyboardShouldPersistTaps="handled"><Text style={styles.label}>Username</Text><TextInput style={styles.input} value={username} onChangeText={setUsername} autoCapitalize="none" placeholder="perfil_sem_arroba" maxLength={31} /><Text style={styles.label}>Nome ou apelido</Text><TextInput style={styles.input} value={displayName} onChangeText={setDisplayName} placeholder="Como você identifica este perfil" maxLength={160} /><Text style={styles.label}>Observações</Text><TextInput style={[styles.input, styles.textarea]} value={notes} onChangeText={setNotes} multiline placeholder="Motivo da referência, temas e observações" maxLength={2000} />{error && <Text style={styles.errorText}>{error}</Text>}<TouchableOpacity style={[historyStyles.button, saving && styles.disabled]} onPress={submit} disabled={saving}>{saving ? <ActivityIndicator color="#fff" /> : <Ionicons name="checkmark" size={20} color="#fff" />}<Text style={historyStyles.buttonText}>Salvar</Text></TouchableOpacity></ScrollView></View></KeyboardAvoidingView>;
}

export default function Concorrentes() {
  const [items, setItems] = useState<Competitor[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [formOpen, setFormOpen] = useState(false);
  const [editing, setEditing] = useState<Competitor | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setItems((await getCompetitors()).items); } catch (caught) { setError(caught instanceof Error ? caught.message : "Não foi possível carregar os perfis."); } finally { setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  async function save(input: CompetitorInput) { if (saving) return; setSaving(true); try { if (editing) await updateCompetitor(editing.id, input); else await createCompetitor(input); setFormOpen(false); setEditing(null); await load(); } catch (caught) { Alert.alert("Concorrentes", caught instanceof Error ? caught.message : "Não foi possível salvar."); } finally { setSaving(false); } }
  function remove(item: Competitor) { Alert.alert("Excluir referência", `Deseja excluir @${item.username}?`, [{ text: "Cancelar", style: "cancel" }, { text: "Excluir", style: "destructive", onPress: () => void deleteCompetitor(item.id).then(load).catch((caught) => Alert.alert("Concorrentes", caught instanceof Error ? caught.message : "Não foi possível excluir.")) }]); }
  return <HistoryScreen title="Concorrentes" subtitle="Perfis de referência cadastrados manualmente"><View style={styles.notice}><Ionicons name="information-circle-outline" size={22} color="#7C3AED" /><Text style={styles.noticeText}>Métricas externas não estão disponíveis neste fluxo oficial. O cadastro serve para organização manual e não consulta nem monitora o perfil informado.</Text></View><TouchableOpacity style={historyStyles.button} onPress={() => { setEditing(null); setFormOpen(true); }}><Ionicons name="add" size={22} color="#fff" /><Text style={historyStyles.buttonText}>Cadastrar perfil</Text></TouchableOpacity>{loading ? <View style={styles.center}><ActivityIndicator color="#d62976" size="large" /></View> : error ? <View style={historyStyles.card}><Text style={historyStyles.heading}>Não foi possível carregar</Text><Text style={historyStyles.body}>{error}</Text><TouchableOpacity onPress={() => void load()}><Text style={styles.retry}>Tentar novamente</Text></TouchableOpacity></View> : items.length === 0 ? <View style={historyStyles.card}><Ionicons name="trophy-outline" size={28} color="#d62976" /><Text style={historyStyles.heading}>Nenhum perfil cadastrado</Text><Text style={historyStyles.body}>Adicione referências que façam sentido para sua estratégia.</Text></View> : items.map((item) => <View style={historyStyles.card} key={item.id}><View style={styles.cardHeader}><View style={styles.cardIdentity}><View style={styles.avatar}><Text style={styles.avatarText}>{item.username.charAt(0).toUpperCase()}</Text></View><View><Text style={historyStyles.heading}>{item.displayName || `@${item.username}`}</Text>{item.displayName && <Text style={historyStyles.body}>@{item.username}</Text>}</View></View><View style={styles.actions}><TouchableOpacity style={styles.iconButton} onPress={() => { setEditing(item); setFormOpen(true); }} accessibilityLabel="Editar"><Ionicons name="pencil-outline" size={19} color="#555" /></TouchableOpacity><TouchableOpacity style={styles.iconButton} onPress={() => remove(item)} accessibilityLabel="Excluir"><Ionicons name="trash-outline" size={19} color="#C53535" /></TouchableOpacity></View></View>{item.notes && <Text style={styles.notes}>{item.notes}</Text>}<View style={styles.unavailable}><Ionicons name="remove-circle-outline" size={16} color="#777" /><Text style={styles.unavailableText}>Métricas não disponíveis</Text></View></View>)}<Modal visible={formOpen} transparent animationType="slide" onRequestClose={() => setFormOpen(false)}>{formOpen && <CompetitorForm item={editing} saving={saving} onClose={() => { setFormOpen(false); setEditing(null); }} onSave={(input) => void save(input)} />}</Modal></HistoryScreen>;
}

const styles = StyleSheet.create({
  notice: { backgroundColor: "#F3EDFF", borderRadius: 8, padding: 14, marginBottom: 16, flexDirection: "row", gap: 10 }, noticeText: { color: "#4E3475", flex: 1, fontSize: 13, lineHeight: 19 }, center: { paddingVertical: 44 }, retry: { color: "#d62976", fontWeight: "800", marginTop: 12 }, cardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" }, cardIdentity: { flex: 1, flexDirection: "row", alignItems: "center", gap: 12 }, avatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: "#FCE7F1", alignItems: "center", justifyContent: "center" }, avatarText: { color: "#d62976", fontWeight: "800", fontSize: 18 }, actions: { flexDirection: "row" }, iconButton: { width: 40, height: 40, alignItems: "center", justifyContent: "center" }, notes: { color: "#555", fontSize: 14, lineHeight: 20, marginTop: 12 }, unavailable: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 14 }, unavailableText: { color: "#777", fontSize: 12, fontWeight: "700" }, overlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.45)", justifyContent: "center", padding: 18 }, modal: { width: "100%", maxWidth: 600, maxHeight: "90%", alignSelf: "center", backgroundColor: "#fff", borderRadius: 8, padding: 20 }, modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, modalTitle: { fontSize: 21, fontWeight: "800", color: "#1E1E1E" }, label: { fontSize: 13, fontWeight: "700", color: "#333", marginTop: 14, marginBottom: 7 }, input: { minHeight: 48, borderWidth: 1, borderColor: "#DEDEE3", borderRadius: 8, paddingHorizontal: 13, backgroundColor: "#FAFAFB", color: "#222" }, textarea: { minHeight: 110, paddingTop: 12, textAlignVertical: "top" }, errorText: { color: "#B52D2D", marginVertical: 12 }, disabled: { opacity: 0.6 },
});
